# Site settings
title: 
email: feather.rw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is mostly a place for me to collect my thoughts in a more 
  structured and "front facing" way.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rwfeather.github.io" # the base hostname & protocol for your site
twitter_username: rwfeather
github_username:  rwfeather

# Build settings
markdown: kramdown
